# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-10 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0009_auto_20170210_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('created_by', models.IntegerField(null=True)),
                ('biller_number', models.CharField(db_index=True, max_length=50)),
                ('late_charge_type', models.CharField(choices=[('F', 'Fixed amount'), ('P', 'Percentage of payment')], max_length=1)),
                ('late_charge_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('late_charge_threshold', models.DecimalField(decimal_places=2, max_digits=7)),
                ('late_charge_min_days', models.SmallIntegerField()),
                ('fiscal_month', models.SmallIntegerField()),
                ('cycle_day', models.SmallIntegerField()),
                ('small_balance_threshold', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_service_start', models.DateField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1)),
                ('bill_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structures.Person')),
                ('officer_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structures.Person')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structures.Person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structures.Person')),
                ('primary_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structures.Person')),
            ],
            options={
                'db_table': 'biller',
                'verbose_name_plural': 'Biller Book',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('created_by', models.IntegerField(null=True)),
                ('fund_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('past_due_days_1', models.SmallIntegerField()),
                ('past_due_days_2', models.SmallIntegerField()),
                ('past_due_days_3', models.SmallIntegerField()),
                ('past_due_days_4', models.SmallIntegerField()),
                ('past_due_days_5', models.SmallIntegerField()),
                ('bill_lead_days', models.SmallIntegerField()),
                ('accrual_days_per_year', models.SmallIntegerField()),
                ('accrual_method', models.CharField(choices=[('S', 'Simple interest'), ('F', 'Fixed days')], max_length=1)),
            ],
            options={
                'db_table': 'fund',
                'verbose_name_plural': 'Fund Book',
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('created_by', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('default_interest_rate', models.DecimalField(decimal_places=5, max_digits=7)),
                ('grace_months', models.SmallIntegerField()),
                ('max_terms', models.SmallIntegerField()),
                ('min_monthly_payment', models.DecimalField(decimal_places=2, max_digits=7)),
                ('min_quarterly_payment', models.DecimalField(decimal_places=2, max_digits=7)),
                ('min_yearly_payment', models.DecimalField(decimal_places=2, max_digits=7)),
                ('allow_deferments', models.BooleanField(default=True)),
                ('allow_cancellations', models.BooleanField(default=True)),
                ('origination_fee', models.DecimalField(decimal_places=2, max_digits=7)),
                ('accrual_method', models.CharField(choices=[('S', 'Simple interest'), ('F', 'Fixed days')], max_length=1)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lenders.Fund')),
                ('initial_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structures.Status')),
            ],
            options={
                'db_table': 'loan_type',
                'verbose_name_plural': 'Loan Types Book',
            },
        ),
    ]
