# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-05 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0005_country_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
