# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-10 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0008_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('E', 'Enrolled'), ('G', 'Grace'), ('P', 'Post-deferment grace'), ('D', 'Deferment'), ('O', 'Postponement'), ('A', 'Active repayment'), ('T', 'Temporary'), ('B', 'Bankruptcy'), ('S', 'Assigned'), ('Z', 'Closed')], max_length=1)),
                ('accrue_flag', models.BooleanField(default=True)),
                ('statements_flag', models.BooleanField(default=True)),
                ('print_past_due_flag', models.BooleanField(default=True)),
                ('aging_flag', models.BooleanField(default=True)),
                ('credit_bureau_flag', models.BooleanField(default=False)),
                ('print_journal_flag', models.BooleanField(default=True)),
                ('next_status', models.IntegerField()),
                ('count_months_effective', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'status',
                'verbose_name_plural': 'Status Code Book',
            },
        ),
        migrations.CreateModel(
            name='TranCode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('short', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=50)),
                ('drcr', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit'), ('N', 'N/A')], max_length=1)),
                ('affects', models.CharField(choices=[('A', 'All balances'), ('C', 'Collection costs'), ('G', 'Litigation costs'), ('I', 'Interest'), ('L', 'Late fees'), ('N', 'N/A'), ('P', 'Principal')], max_length=1)),
                ('table_id', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'tran_code',
                'verbose_name_plural': 'Transaction Code Book',
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='account',
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structures.Country'),
        ),
        migrations.AlterField(
            model_name='person',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structures.Entity'),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structures.State'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tax_id',
            field=models.CharField(db_index=True, max_length=15, null=True),
        ),
    ]
