# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0009_auto_20170210_1637'),
        ('borrowers', '0002_auto_20170211_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('created_by', models.IntegerField(null=True)),
                ('batch', models.BigIntegerField(db_index=True)),
                ('sequence', models.SmallIntegerField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('coll_fee', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('lit_fee', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('effective_date', models.DateField(db_index=True)),
                ('thru_date', models.DateField(null=True)),
                ('reversed', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=50, null=True)),
                ('source_id', models.CharField(choices=[('S', 'System generated'), ('U', 'User generated'), ('B', 'Biller generated'), ('P', 'Payer generated'), ('C', 'Conversion')], max_length=1)),
                ('reference', models.IntegerField(null=True)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='borrowers.Obligation')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='borrowers.Payer')),
                ('tran_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structures.TranCode')),
            ],
            options={
                'db_table': 'history',
                'verbose_name_plural': 'Transaction History',
            },
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together=set([('batch', 'sequence')]),
        ),
    ]
