# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-05 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0002_auto_20170205_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
