# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-05 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0003_auto_20170205_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='entity',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
