# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-05 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0006_auto_20170205_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('name_fr', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'country',
                'verbose_name_plural': 'Country Book',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'state',
                'verbose_name_plural': 'State Book',
            },
        ),
    ]
