# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-10 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0009_auto_20170210_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structures.Person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structures.Person')),
            ],
            options={
                'db_table': 'coll_agency',
                'verbose_name_plural': 'Collection Agency Book',
            },
        ),
    ]
