# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-10 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lenders', '0001_initial'),
        ('vendors', '0001_initial'),
        ('structures', '0009_auto_20170210_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('created_by', models.IntegerField(null=True)),
                ('sequence', models.SmallIntegerField()),
                ('status_expires', models.DateField(null=True)),
                ('interest_rate', models.FloatField()),
                ('payment_split', models.DecimalField(decimal_places=2, max_digits=7)),
                ('original_principal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('principal_paid_ltd', models.DecimalField(decimal_places=2, max_digits=9)),
                ('principal_cancelled_ltd', models.DecimalField(decimal_places=2, max_digits=9)),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=9)),
                ('principal_past_due', models.DecimalField(decimal_places=2, max_digits=9)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=9)),
                ('interest_past_due', models.DecimalField(decimal_places=2, max_digits=9)),
                ('interest_paid_ltd', models.DecimalField(decimal_places=2, max_digits=9)),
                ('interest_cancelled_ltd', models.DecimalField(decimal_places=2, max_digits=9)),
                ('interest_accrued', models.DecimalField(decimal_places=5, max_digits=11)),
                ('interest_capitalized_ltd', models.DecimalField(decimal_places=2, max_digits=9)),
                ('late_fee_due', models.DecimalField(decimal_places=2, max_digits=7)),
                ('late_fee_paid_ltd', models.DecimalField(decimal_places=2, max_digits=7)),
                ('collection_fee_due', models.DecimalField(decimal_places=2, max_digits=7)),
                ('collection_fee_paid_ltd', models.DecimalField(decimal_places=2, max_digits=7)),
                ('litigation_fee_due', models.DecimalField(decimal_places=2, max_digits=7)),
                ('litigation_fee_paid_ltd', models.DecimalField(decimal_places=2, max_digits=7)),
                ('service_fee_due', models.DecimalField(decimal_places=2, max_digits=7)),
                ('service_fee_paid_ltd', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payoff', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date_opened', models.DateTimeField()),
                ('date_separated', models.DateTimeField(null=True)),
                ('date_first_payment', models.DateField(null=True)),
                ('principal_next_due', models.DateField()),
                ('interest_next_due', models.DateField()),
                ('date_last_accrual', models.DateField(null=True)),
                ('number_terms', models.SmallIntegerField()),
                ('number_terms_remaining', models.SmallIntegerField()),
                ('days_past_due', models.SmallIntegerField()),
                ('date_principal_changed', models.DateField()),
                ('date_status_changed', models.DateField()),
                ('date_closed', models.DateField(null=True)),
                ('closed_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structures.TranCode')),
                ('loan_type', models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lenders.LoanType')),
            ],
            options={
                'db_table': 'obligation',
                'verbose_name_plural': 'Obligations Book',
            },
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('created_by', models.IntegerField(null=True)),
                ('account', models.CharField(max_length=50)),
                ('principal_freq', models.CharField(choices=[('W', 'Weekly'), ('B', 'Bi-weekly'), ('M', 'Monthly'), ('2', 'Bi-monthly'), ('Q', 'Quarterly'), ('S', 'Semi-annually'), ('Y', 'Yearly')], max_length=1)),
                ('interest_freq', models.CharField(choices=[('W', 'Weekly'), ('B', 'Bi-weekly'), ('M', 'Monthly'), ('2', 'Bi-monthly'), ('Q', 'Quarterly'), ('S', 'Semi-annually'), ('Y', 'Yearly')], max_length=1)),
                ('interest_type', models.CharField(choices=[('A', 'Interest added on'), ('I', 'Included in payment'), ('O', 'Interest only'), ('N', 'Non interest bearing')], max_length=1)),
                ('billing_type', models.CharField(choices=[('P', 'Paper statement'), ('E', 'Electronic notification'), ('A', 'Automatic withdrawal'), ('C', 'Coupon'), ('T', 'Text message')], max_length=1)),
                ('next_bill_date', models.DateField()),
                ('hold_bill_until', models.DateField(null=True)),
                ('min_pay', models.DecimalField(decimal_places=2, max_digits=7)),
                ('temp_min_pay', models.DecimalField(decimal_places=2, max_digits=7)),
                ('temp_min_pay_until', models.DateField(null=True)),
                ('last_activity', models.DateTimeField()),
                ('last_payment_date', models.DateField()),
                ('last_payment_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('credit_bureau_report', models.BooleanField(default=False)),
                ('cycle_day', models.SmallIntegerField(default=1)),
                ('past_due_cnt_15', models.SmallIntegerField()),
                ('past_due_cnt_30', models.SmallIntegerField()),
                ('past_due_cnt_60', models.SmallIntegerField()),
                ('past_due_cnt_90', models.SmallIntegerField()),
                ('past_due_cnt_120', models.SmallIntegerField()),
                ('biller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lenders.Biller')),
                ('collection_agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vendors.Agency')),
                ('cosigner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structures.Person')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lenders.Fund')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structures.Person')),
            ],
            options={
                'db_table': 'payer',
                'verbose_name_plural': 'Payer Book',
            },
        ),
        migrations.AddField(
            model_name='obligation',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='borrowers.Payer'),
        ),
        migrations.AddField(
            model_name='obligation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structures.Status'),
        ),
    ]
