# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-11 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='account',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
